"""Phc2sysConfig – parser/serializer for /etc/linuxptp/phc2sys.conf.

Format: [global] section header (optional), then key<whitespace>value lines.
Comments start with #. Save writes only values differing from built-in defaults.
"""

import os
import shutil
from pathlib import Path

from .phc2sys_config_meta import BUILTIN_DEFAULTS


CONFIG_DIR = '/etc/linuxptp'
CONFIG_PATH = os.path.join(CONFIG_DIR, 'phc2sys.conf')


class Phc2sysConfigError(Exception):
    ...


class Phc2sysConfig:
    def __init__(self):
        self._data = {}
        self._loaded_path = None
        self._dirty = set()

    # ─── Public API ──────────────────────────────────────────

    def load(self, path):
        self._loaded_path = str(path)
        self._data = {}
        self._dirty = set()
        try:
            with open(self._loaded_path) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#') or line.startswith('['):
                        continue
                    parts = line.split(None, 1)
                    if len(parts) == 2:
                        key, val = parts
                        self._data[key] = self._parse_value(val)
        except FileNotFoundError:
            raise Phc2sysConfigError(f"Config not found: {self._loaded_path}")

    def save(self, path=None):
        path = str(path or self._loaded_path)
        if not path:
            raise Phc2sysConfigError("No path specified")
        if os.path.exists(path):
            shutil.copy(path, path + '.bak')

        Path(path).parent.mkdir(parents=True, exist_ok=True)

        lines = [
            '# phc2sys.conf – generated by sync67',
            '# Only parameters with non-default values are listed.',
            '# phc2sys uses built-in defaults for missing parameters.',
            '',
            '[global]',
        ]

        dirty_keys = set(self._dirty)
        deleted_keys = {k.replace('__delete__', '') for k in dirty_keys if k.startswith('__delete__')}
        dirty_keys = {k for k in dirty_keys if not k.startswith('__delete__')}

        # Include keys from file that are not dirty and differ from defaults
        for key, val in self._data.items():
            if key not in dirty_keys and key not in deleted_keys and val != BUILTIN_DEFAULTS.get(key):
                dirty_keys.add(key)

        for key in sorted(dirty_keys):
            if key in deleted_keys:
                continue
            val = self._data[key]
            lines.append(f'{key} {self._format_value(val)}')

        lines.append('')
        text = '\n'.join(lines)

        with open(path, 'w') as f:
            f.write(text)

        self._dirty = set()

    def get(self, key):
        return self._data.get(key)

    def set(self, key, value):
        if key in self._data and self._data[key] == value:
            return False
        self._data[key] = value
        self._dirty.discard(f'__delete__{key}')
        self._dirty.add(key)
        return True

    def delete(self, key):
        if key in self._data:
            del self._data[key]
            self._dirty.discard(key)
            self._dirty.add(f'__delete__{key}')

    def reset_to_default(self):
        self._data = {}
        self._dirty = set()
        self.save()
        return True

    def create_default(self, path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as f:
            f.write('# phc2sys.conf – generated by sync67\n'
                    '# Only parameters with non-default values are listed.\n'
                    '# phc2sys uses built-in defaults for missing parameters.\n'
                    '\n'
                    '[global]\n')
        self._loaded_path = str(path)
        self._data = {}
        self._dirty = set()

    def get_loaded_path(self):
        return self._loaded_path

    # ─── Parsing / Formatting ───────────────────────────────

    def _parse_value(self, val):
        val = val.strip()
        if val.lower() in ('true', 'yes', 'on'):
            return 1
        if val.lower() in ('false', 'no', 'off'):
            return 0
        try:
            if '.' in val:
                return float(val)
            return int(val)
        except (ValueError, TypeError):
            pass
        return val

    @staticmethod
    def _format_value(val):
        if isinstance(val, bool):
            return '1' if val else '0'
        if isinstance(val, int):
            return str(val)
        if isinstance(val, float):
            return str(val)
        return str(val)
