"""Parameter-Definitionen für /etc/linuxptp/ptp4l.conf."""


class ParamDef:
    __slots__ = ('key', 'type', 'default', 'label', 'tooltip',
                 'section', 'choices', 'min_val', 'max_val', 'step')

    def __init__(self, key, ptype, default, label='', tooltip='',
                 section='Quick', choices=None,
                 min_val=None, max_val=None, step=None):
        self.key = key
        self.type = ptype
        self.default = default
        self.label = label or key
        self.tooltip = tooltip
        self.section = section
        self.choices = choices or []
        self.min_val = min_val
        self.max_val = max_val
        self.step = step


def _int_choices(*vals):
    return list(vals)

LOG_INTERVALS = [(-3, '128 Hz'), (-2, '64 Hz'), (-1, '2 Hz (512 ms)'),
                 (0, '1 Hz (1 s)'), (1, '0.5 Hz (2 s)'), (2, '0.25 Hz (4 s)'),
                 (3, '0.125 Hz (8 s)'), (4, '1/16 Hz (16 s)')]


CONFIG_PARAMS = [

    # ── Quick (10 wichtigste Parameter) ──────────────────────
    ParamDef('clientOnly', 'bool', 0,
             label='Client Only',
             tooltip='Nur als PTP-Client arbeiten, niemals Master werden.',
             section='Quick'),
    ParamDef('priority1', 'int', 128,
             label='Priority 1',
             tooltip='Erste Priorität des Clocks (0-255).\nNiedriger = höhere Wahrscheinlichkeit zum Master.',
             section='Quick', min_val=0, max_val=255),
    ParamDef('priority2', 'int', 128,
             label='Priority 2',
             tooltip='Zweite Priorität des Clocks (0-255).\nNiedriger = höhere Wahrscheinlichkeit zum Master.',
             section='Quick', min_val=0, max_val=255),
    ParamDef('verbose', 'bool', 0,
             label='Verbose Output',
             tooltip='Ausführliche Log-Ausgabe aktivieren.',
             section='Quick'),
    ParamDef('network_transport', 'choice', 'UDPv4',
             label='Network Transport',
             tooltip='Transportprotokoll für PTP-Nachrichten.',
             section='Quick',
             choices=['UDPv4', 'UDPv6', 'L2']),
    ParamDef('time_stamping', 'choice', 'hardware',
             label='Time Stamping',
             tooltip='Methode für Hardware-Zeitstempel.\n'
                     'hardware = PHC (genauer)\nsoftware = Software-Timestamps (kein PHC nötig)',
             section='Quick',
             choices=['hardware', 'software']),
    ParamDef('SlaveOnly', 'bool', 0,
             label='Slave Only',
             tooltip='Nur als Slave arbeiten, Client-tauglich.\nÜberschreibt clock_type.',
             section='Quick'),
    ParamDef('MasterOnly', 'bool', 0,
             label='Master Only',
             tooltip='Nur als Master arbeiten.\nÜberschreibt clock_type.',
             section='Quick'),
    ParamDef('logSyncInterval', 'choice', 0,
             label='Sync Interval',
             tooltip='Intervall der Sync-Nachrichten.\nWert = log2(Interval in Sekunden).\n0 = 1 Hz (1 s), -3 = 128 Hz.',
             section='Quick',
             choices=[-3, -2, -1, 0, 1, 2, 3, 4]),
    ParamDef('logMinDelayReqInterval', 'choice', 0,
             label='Delay Request Interval',
             tooltip='Minimales Intervall für Delay-Requests.\n0 = 1 Hz (1 s), -3 = 128 Hz.',
             section='Quick',
             choices=[-3, -2, -1, 0, 1, 2, 3, 4]),

    # ── Default Data Set ─────────────────────────────────────
    ParamDef('twoStepFlag', 'bool', 1,
             label='Two-Step Flag',
             tooltip='Zwei-Schritt-Modus für PTP-Nachrichten.\n'
                     '1 = Follow-Up Nachricht senden.',
             section='Default'),
    ParamDef('socket_priority', 'int', 0,
             label='Socket Priority',
             tooltip='Priorität der Netzwerk-Sockets.\n'
                     'Höher = bevorzugte Behandlung im Netzwerkstack.',
             section='Default', min_val=0, max_val=15),
    ParamDef('domainNumber', 'int', 0,
             label='Domain Number',
             tooltip='PTP-Domain (0-255).\n'
                     'Alle Geräte in einer Domain müssen die gleiche Nummer haben.',
             section='Default', min_val=0, max_val=255),
    ParamDef('utc_offset', 'int', 37,
             label='UTC Offset',
             tooltip='TAI-UTC Offset in Sekunden.\n'
                     'Wird automatisch aktualisiert wenn bekannt.',
             section='Default', min_val=0, max_val=60),
    ParamDef('clockClass', 'int', 248,
             label='Clock Class',
             tooltip='Clock-Klasse nach IEEE 1588-2008.\n'
                     '248 = Standard für NICs ohne GPS.',
             section='Default', min_val=0, max_val=255),
    ParamDef('clockAccuracy', 'string', '0xFE',
             label='Clock Accuracy',
             tooltip='Clock-Genauigkeit im IEEE-Format.\n0xFE = unknown (typisch für NICs).',
             section='Default'),
    ParamDef('offsetScaledLogVariance', 'string', '0xFFFF',
             label='Offset Scaled Log Variance',
             tooltip='Varianz der Clock-Offset-Schätzung.\n0xFFFF = Standardwert.',
             section='Default'),
    ParamDef('free_running', 'bool', 0,
             label='Free Running',
             tooltip='Clock läuft frei, keine Synchronisation.\n'
                     'Nützlich zum Testen ohne PTP-Master.',
             section='Default'),
    ParamDef('freq_est_interval', 'int', 1,
             label='Frequency Estimation Interval',
             tooltip='Intervall für Frequenzschätzung in Sekunden.',
             section='Default', min_val=0, max_val=60),
    ParamDef('dscp_event', 'int', 0,
             label='DSCP Event',
             tooltip='DSCP-Wert für Event-Nachrichten.\n0 = Standard.',
             section='Default', min_val=0, max_val=63),
    ParamDef('dscp_general', 'int', 0,
             label='DSCP General',
             tooltip='DSCP-Wert für allgemeine Nachrichten.\n0 = Standard.',
             section='Default', min_val=0, max_val=63),
    ParamDef('dataset_comparison', 'choice', 'ieee1588',
             label='Dataset Comparison',
             tooltip='Algorithmus für Dataset-Vergleich.\nieee1588 = Standard.',
             section='Default',
             choices=['ieee1588', 'G.8275.1']),
    ParamDef('G.8275.defaultDS.localPriority', 'int', 128,
             label='G.8275 Local Priority',
             tooltip='Lokale Priorität für G.8275.1-Profil.\nNiedriger = höher.',
             section='Default', min_val=0, max_val=255),
    ParamDef('maxStepsRemoved', 'int', 255,
             label='Max Steps Removed',
             tooltip='Maximale Anzahl BC-Sprünge zum Grandmaster.\n255 = unbegrenzt.',
             section='Default', min_val=0, max_val=255),

    # ── Port Data Set ────────────────────────────────────────
    ParamDef('logAnnounceInterval', 'choice', 1,
             label='Announce Interval',
             tooltip='Intervall der Announce-Nachrichten.\n1 = 0.5 Hz (alle 2 s).',
             section='Port',
             choices=[-3, -2, -1, 0, 1, 2, 3, 4]),
    ParamDef('operLogSyncInterval', 'int', 0,
             label='Operational Sync Interval',
             tooltip='Tatsächliches Sync-Intervall (wenn abweichend).',
             section='Port', min_val=-128, max_val=127),
    ParamDef('logMinPdelayReqInterval', 'int', 0,
             label='Pdelay Request Interval',
             tooltip='Intervall für Peer-Delay-Requests (P2P).',
             section='Port', min_val=-128, max_val=127),
    ParamDef('operLogPdelayReqInterval', 'int', 0,
             label='Operational Pdelay Interval',
             tooltip='Tatsächliches Peer-Delay-Intervall.',
             section='Port', min_val=-128, max_val=127),
    ParamDef('announceReceiptTimeout', 'int', 3,
             label='Announce Receipt Timeout',
             tooltip='Anzahl verpasster Announce-Nachrichten bevor Master gewechselt wird.',
             section='Port', min_val=2, max_val=10),
    ParamDef('syncReceiptTimeout', 'int', 0,
             label='Sync Receipt Timeout',
             tooltip='Timeout für Sync-Empfang.\n0 = deaktiviert.',
             section='Port', min_val=0, max_val=10),
    ParamDef('delay_request_variability', 'float', 1.0,
             label='Delay Request Variability',
             tooltip='Variabilität des Delay-Request-Intervalls (1.0 = fest).',
             section='Port', min_val=0.0, max_val=10.0),
    ParamDef('delay_response_timeout', 'int', 0,
             label='Delay Response Timeout',
             tooltip='Timeout für Delay-Response.\n0 = deaktiviert.',
             section='Port', min_val=0, max_val=60),
    ParamDef('delayAsymmetry', 'int', 0,
             label='Delay Asymmetry',
             tooltip='Asymmetrie der Leitungslaufzeit in Nanosekunden.\n'
                     'Positiv = Hinweg länger als Rückweg.',
             section='Port', min_val=-1000000, max_val=1000000),
    ParamDef('fault_reset_interval', 'int', 4,
             label='Fault Reset Interval',
             tooltip='Intervall zum Zurücksetzen von Fehlern (log2 Sekunden).\n4 = 16 s.',
             section='Port', min_val=0, max_val=7),
    ParamDef('neighborPropDelayThresh', 'int', 20000000,
             label='Neighbor Prop Delay Threshold',
             tooltip='Maximale Nachbarschafts-Laufzeit in ns.\n20 ms = typischer Schwellwert.',
             section='Port', min_val=0, max_val=100000000),
    ParamDef('serverOnly', 'bool', 0,
             label='Server Only',
             tooltip='Nur als Server arbeiten (Unicast).',
             section='Port'),
    ParamDef('G.8275.portDS.localPriority', 'int', 128,
             label='G.8275 Port Local Priority',
             tooltip='Lokale Port-Priorität für G.8275.1.',
             section='Port', min_val=0, max_val=255),
    ParamDef('allowedLostResponses', 'int', 3,
             label='Allowed Lost Responses',
             tooltip='Erlaubte Fehlversuche bevor Verbindung getrennt wird.',
             section='Port', min_val=0, max_val=10),
    ParamDef('asCapable', 'choice', 'auto',
             label='AS Capable',
             tooltip='Peer-to-Peer-Fähigkeit.\nauto = automatische Erkennung.',
             section='Port',
             choices=['auto', 'true', 'false']),
    ParamDef('BMCA', 'choice', 'ptp',
             label='Best Master Clock Algorithm',
             tooltip='Algorithmus zur Master-Auswahl.\nptp = IEEE 1588 Standard.',
             section='Port',
             choices=['ptp', 'G.8275.1']),
    ParamDef('inhibit_announce', 'bool', 0,
             label='Inhibit Announce',
             tooltip='Announce-Nachrichten unterdrücken.',
             section='Port'),
    ParamDef('inhibit_delay_req', 'bool', 0,
             label='Inhibit Delay Request',
             tooltip='Delay-Requests unterdrücken.',
             section='Port'),
    ParamDef('ignore_source_id', 'bool', 0,
             label='Ignore Source ID',
             tooltip='Source-ID von PTP-Nachrichten ignorieren.\n'
                     'Nützlich bei proprietären Implementierungen.',
             section='Port'),
    ParamDef('power_profile.2011.grandmasterTimeInaccuracy', 'int', -1,
             label='Power Profile GM Time Inaccuracy',
             tooltip='Grandmaster-Zeitungenauigkeit (IEC 61850-9-3).\n-1 = nicht gesetzt.',
             section='Port', min_val=-1, max_val=100000),
    ParamDef('power_profile.2011.networkTimeInaccuracy', 'int', -1,
             label='Power Profile Network Time Inaccuracy',
             tooltip='Netzwerk-Zeitungenauigkeit (IEC 61850-9-3).',
             section='Port', min_val=-1, max_val=100000),
    ParamDef('power_profile.2017.totalTimeInaccuracy', 'int', -1,
             label='Power Profile 2017 Total Time Inaccuracy',
             tooltip='Gesamt-Zeitungenauigkeit (IEEE C37.238-2017).',
             section='Port', min_val=-1, max_val=100000),
    ParamDef('power_profile.grandmasterID', 'int', 0,
             label='Power Profile Grandmaster ID',
             tooltip='Grandmaster-ID für Power Profile.\n0 = automatisch.',
             section='Port', min_val=0, max_val=255),
    ParamDef('power_profile.version', 'choice', 'none',
             label='Power Profile Version',
             tooltip='Power-Profile-Version:\nnone = deaktiviert.',
             section='Port',
             choices=['none', '2011', '2017']),
    ParamDef('ptp_minor_version', 'int', 1,
             label='PTP Minor Version',
             tooltip='Minor-Version des PTP-Protokolls.\n1 = IEEE 1588-2019.',
             section='Port', min_val=0, max_val=1),
    ParamDef('spp', 'int', -1,
             label='SPP',
             tooltip='TransportSpecific + minorVersion.\n'
                     '-1 = automatisch aus transportSpecific.',
             section='Port', min_val=-1, max_val=255),
    ParamDef('active_key_id', 'int', 0,
             label='Active Key ID',
             tooltip='Aktive Schlüssel-ID für AES-CMAC (Sicherheit).\n0 = deaktiviert.',
             section='Port', min_val=0, max_val=255),

    # ── Run Time Options ──────────────────────────────────────
    ParamDef('assume_two_step', 'bool', 0,
             label='Assume Two-Step',
             tooltip='Annahme des Zwei-Schritt-Modus auch bei einstufigen Nachrichten.',
             section='Runtime'),
    ParamDef('logging_level', 'int', 6,
             label='Logging Level',
             tooltip='Log-Level (0-7).\n6 = Info, 7 = Debug.',
             section='Runtime', min_val=0, max_val=7),
    ParamDef('path_trace_enabled', 'bool', 0,
             label='Path Trace',
             tooltip='Pfad-Tracing aktivieren für PTP-Topologie-Erkennung.',
             section='Runtime'),
    ParamDef('follow_up_info', 'bool', 0,
             label='Follow-Up Info',
             tooltip='Zusätzliche Informationen in Follow-Up-Nachrichten.',
             section='Runtime'),
    ParamDef('hybrid_e2e', 'bool', 0,
             label='Hybrid E2E',
             tooltip='Hybrider End-to-End-Modus (Multicast + Unicast).',
             section='Runtime'),
    ParamDef('inhibit_multicast_service', 'bool', 0,
             label='Inhibit Multicast Service',
             tooltip='Multicast-Dienst unterdrücken.\nNützlich für reine Unicast-Umgebungen.',
             section='Runtime'),
    ParamDef('net_sync_monitor', 'bool', 0,
             label='Network Sync Monitor',
             tooltip='Netzwerk-Sync-Monitor aktivieren.',
             section='Runtime'),
    ParamDef('tc_spanning_tree', 'bool', 0,
             label='TC Spanning Tree',
             tooltip='Spanning-Tree-Unterstützung für Transparent Clocks.',
             section='Runtime'),
    ParamDef('tx_timestamp_timeout', 'int', 10,
             label='TX Timestamp Timeout',
             tooltip='Timeout für TX-Timestamps in Millisekunden.\n'
                     'Erhöhen bei vielen Paketen, 10 = Standard.',
             section='Runtime', min_val=1, max_val=100),
    ParamDef('unicast_listen', 'bool', 0,
             label='Unicast Listen',
             tooltip='Auf Unicast-Verbindungen warten.',
             section='Runtime'),
    ParamDef('unicast_master_table', 'int', 0,
             label='Unicast Master Table',
             tooltip='Tabelle der Unicast-Master.\n0 = deaktiviert.',
             section='Runtime', min_val=0, max_val=255),
    ParamDef('unicast_req_duration', 'int', 3600,
             label='Unicast Request Duration',
             tooltip='Dauer der Unicast-Anfrage in Sekunden.\n3600 = 1 Stunde.',
             section='Runtime', min_val=0, max_val=86400),
    ParamDef('use_syslog', 'bool', 1,
             label='Use Syslog',
             tooltip='Logs auch via Syslog ausgeben.',
             section='Runtime'),
    ParamDef('summary_interval', 'int', 0,
             label='Summary Interval',
             tooltip='Intervall für Zusammenfassungs-Logs (log2 Sekunden).\n0 = jede Sekunde.',
             section='Runtime', min_val=0, max_val=10),
    ParamDef('kernel_leap', 'bool', 1,
             label='Kernel Leap',
             tooltip='Kernel-Schaltsekunden-Unterstützung aktivieren.',
             section='Runtime'),
    ParamDef('check_fup_sync', 'bool', 0,
             label='Check Follow-Up Sync',
             tooltip='Follow-Up-Timestamps gegen Sync prüfen (QoS).',
             section='Runtime'),
    ParamDef('clock_class_threshold', 'int', 248,
             label='Clock Class Threshold',
             tooltip='Schwellwert für Clock-Class-Akzeptanz.\n'
                     'Nur Master mit Class < Threshold werden akzeptiert.',
             section='Runtime', min_val=0, max_val=255),

    # ── Servo Options ─────────────────────────────────────────
    ParamDef('pi_proportional_const', 'float', 0.0,
             label='PI Proportional Constant',
             tooltip='Proportional-Konstante des PI-Reglers.\n0.0 = Standard.',
             section='Servo', min_val=0.0, max_val=1.0),
    ParamDef('pi_integral_const', 'float', 0.0,
             label='PI Integral Constant',
             tooltip='Integral-Konstante des PI-Reglers.\n0.0 = Standard.',
             section='Servo', min_val=0.0, max_val=1.0),
    ParamDef('pi_proportional_scale', 'float', 0.0,
             label='PI Proportional Scale',
             tooltip='Skalierung des Proportional-Anteils.\n0.0 = Standard.',
             section='Servo', min_val=0.0, max_val=10.0),
    ParamDef('pi_proportional_exponent', 'float', -0.3,
             label='PI Proportional Exponent',
             tooltip='Exponent des Proportional-Anteils.\n-0.3 = Standard.',
             section='Servo', min_val=-10.0, max_val=10.0),
    ParamDef('pi_proportional_norm_max', 'float', 0.7,
             label='PI Proportional Norm Max',
             tooltip='Maximale Normalisierung des Proportional-Anteils.',
             section='Servo', min_val=0.0, max_val=10.0),
    ParamDef('pi_integral_scale', 'float', 0.0,
             label='PI Integral Scale',
             tooltip='Skalierung des Integral-Anteils.\n0.0 = Standard.',
             section='Servo', min_val=0.0, max_val=10.0),
    ParamDef('pi_integral_exponent', 'float', 0.4,
             label='PI Integral Exponent',
             tooltip='Exponent des Integral-Anteils.\n0.4 = Standard.',
             section='Servo', min_val=-10.0, max_val=10.0),
    ParamDef('pi_integral_norm_max', 'float', 0.3,
             label='PI Integral Norm Max',
             tooltip='Maximale Normalisierung des Integral-Anteils.',
             section='Servo', min_val=0.0, max_val=10.0),
    ParamDef('step_threshold', 'float', 0.0,
             label='Step Threshold',
             tooltip='Schwellwert für Clock-Sprünge in Sekunden.\n'
                     '0.0 = Sprünge immer erlauben.',
             section='Servo', min_val=0.0, max_val=1.0),
    ParamDef('first_step_threshold', 'float', 0.00002,
             label='First Step Threshold',
             tooltip='Schwellwert für ersten Clock-Sprung (20 µs).\n'
                     'Größerer Wert = größerer erster Schritt.',
             section='Servo', min_val=0.0, max_val=1.0),
    ParamDef('max_frequency', 'int', 900000000,
             label='Max Frequency Adjustment',
             tooltip='Maximale Frequenzkorrektur in ppb.\n'
                     '900000000 = ±900 ppm.',
             section='Servo', min_val=0, max_val=1000000000),
    ParamDef('clock_servo', 'choice', 'pi',
             label='Clock Servo',
             tooltip='Regler-Algorithmus:\npi = PI-Regler (Standard)\n'
                     'linreg = Lineare Regression\nnull = keine Korrektur.',
             section='Servo',
             choices=['pi', 'linreg', 'null']),
    ParamDef('sanity_freq_limit', 'int', 200000000,
             label='Sanity Frequency Limit',
             tooltip='Maximale plausible Frequenzkorrektur in ppb.\n'
                     '200000000 = ±200 ppm.',
             section='Servo', min_val=0, max_val=1000000000),
    ParamDef('refclock_sock_address', 'string', '/var/run/refclock.ptp.sock',
             label='Refclock Socket',
             tooltip='UNIX-Socket für externe Referenz-Clock.',
             section='Servo'),
    ParamDef('ntpshm_segment', 'int', 0,
             label='NTP SHM Segment',
             tooltip='NTP Shared-Memory-Segment für Clock-Einspeisung.',
             section='Servo', min_val=0, max_val=15),
    ParamDef('msg_interval_request', 'int', 0,
             label='Message Interval Request',
             tooltip='Angefordertes Nachrichtenintervall.\n0 = Standard.',
             section='Servo', min_val=-128, max_val=127),
    ParamDef('servo_num_offset_values', 'int', 10,
             label='Servo Offset Values',
             tooltip='Anzahl der Offset-Werte für die Filterung.\n10 = Standard.',
             section='Servo', min_val=1, max_val=100),
    ParamDef('servo_offset_threshold', 'int', 0,
             label='Servo Offset Threshold',
             tooltip='Schwellwert für Offset-Änderungen.\n0 = deaktiviert.',
             section='Servo', min_val=0, max_val=1000000),
    ParamDef('write_phase_mode', 'bool', 0,
             label='Write Phase Mode',
             tooltip='Phasenkorrektur-Modus aktivieren.\n'
                     'Nützlich für PTP-fähige NICs die Phasenanpassung unterstützen.',
             section='Servo'),

    # ── Transport Options ─────────────────────────────────────
    ParamDef('cmlds.client_address', 'string', '/var/run/ptp/cmlds_client',
             label='CMLDS Client Address',
             tooltip='Socket-Adresse für CMLDS-Client.',
             section='Transport'),
    ParamDef('cmlds.domainNumber', 'int', 0,
             label='CMLDS Domain Number',
             tooltip='CMLDS-Domainnummer.',
             section='Transport', min_val=0, max_val=255),
    ParamDef('cmlds.majorSdoId', 'int', 2,
             label='CMLDS Major SdoId',
             tooltip='CMLDS Major SdoId (2 = IEEE 802.1AS).',
             section='Transport', min_val=0, max_val=255),
    ParamDef('cmlds.port', 'int', 0,
             label='CMLDS Port',
             tooltip='CMLDS-Port.',
             section='Transport', min_val=0, max_val=65535),
    ParamDef('cmlds.server_address', 'string', '/var/run/ptp/cmlds_server',
             label='CMLDS Server Address',
             tooltip='Socket-Adresse für CMLDS-Server.',
             section='Transport'),
    ParamDef('transportSpecific', 'string', '0x0',
             label='Transport Specific',
             tooltip='Transport-spezifischer Wert.\n0x0 = IEEE 1588 Standard.',
             section='Transport'),
    ParamDef('ptp_dst_ipv4', 'string', '224.0.1.129',
             label='PTP IPv4 Multicast',
             tooltip='IPv4-Multicast-Adresse für PTP-Nachrichten.\n224.0.1.129 = IEEE 1588.',
             section='Transport'),
    ParamDef('p2p_dst_ipv4', 'string', '224.0.0.107',
             label='P2P IPv4 Multicast',
             tooltip='IPv4-Multicast für Peer-Delay.\n224.0.0.107 = IEEE 1588.',
             section='Transport'),
    ParamDef('ptp_dst_ipv6', 'string', 'FF0E:0:0:0:0:0:0:181',
             label='PTP IPv6 Multicast',
             tooltip='IPv6-Multicast-Adresse für PTP.',
             section='Transport'),
    ParamDef('p2p_dst_ipv6', 'string', 'FF02:0:0:0:0:0:0:6B',
             label='P2P IPv6 Multicast',
             tooltip='IPv6-Multicast für Peer-Delay.',
             section='Transport'),
    ParamDef('ptp_dst_mac', 'string', '01:1B:19:00:00:00',
             label='PTP MAC Multicast',
             tooltip='MAC-Multicast-Adresse für PTP-Events.\n01:1B:19:00:00:00 = IEEE 1588.',
             section='Transport'),
    ParamDef('p2p_dst_mac', 'string', '01:80:C2:00:00:0E',
             label='P2P MAC Multicast',
             tooltip='MAC-Multicast-Adresse für Peer-Delay.',
             section='Transport'),
    ParamDef('udp_ttl', 'int', 1,
             label='UDP TTL',
             tooltip='Time-To-Live für UDP-Pakete.\n1 = nur lokales Subnetz.',
             section='Transport', min_val=1, max_val=255),
    ParamDef('udp6_scope', 'string', '0x0E',
             label='UDP6 Scope',
             tooltip='IPv6-Scope für PTP-Nachrichten.\n0x0E = global.',
             section='Transport'),
    ParamDef('uds_address', 'string', '/var/run/ptp4l',
             label='UDS Address',
             tooltip='UNIX-Domain-Socket für ptp4l Management.\nNur lesend/schreibend vom Admin.',
             section='Transport'),
    ParamDef('uds_file_mode', 'string', '0660',
             label='UDS File Mode',
             tooltip='Dateirechte des UDS-Sockets.\n0660 = Owner + Group r/w.',
             section='Transport'),
    ParamDef('uds_ro_address', 'string', '/var/run/ptp4lro',
             label='UDS Read-Only Address',
             tooltip='UNIX-Domain-Socket für Lese-Zugriff.\nVon ptp4lmanagement-Socket genutzt.',
             section='Transport'),
    ParamDef('uds_ro_file_mode', 'string', '0666',
             label='UDS Read-Only File Mode',
             tooltip='Dateirechte des Read-Only-Sockets.\n0666 = alle lesen/schreiben.',
             section='Transport'),

    # ── Default Interface Options + Clock Description ─────────
    ParamDef('clock_type', 'choice', 'OC',
             label='Clock Type',
             tooltip='Clock-Typ:\nOC = Ordinary Clock\nBC = Boundary Clock\nTC = Transparent Clock.',
             section='Interface',
             choices=['OC', 'BC', 'TC']),
    ParamDef('delay_mechanism', 'choice', 'E2E',
             label='Delay Mechanism',
             tooltip='Laufzeitmessung:\nE2E = End-to-End\nP2P = Peer-to-Peer\nAuto = Automatisch.',
             section='Interface',
             choices=['E2E', 'P2P', 'auto']),
    ParamDef('tsproc_mode', 'choice', 'filter',
             label='Timestamp Processing Mode',
             tooltip='Timestamp-Verarbeitungsmodus.\nfilter = Rohdaten filtern.',
             section='Interface',
             choices=['filter', 'raw']),
    ParamDef('delay_filter', 'choice', 'moving_median',
             label='Delay Filter',
             tooltip='Filter für Laufzeitmessungen.\nmoving_median = gleitender Median.',
             section='Interface',
             choices=['moving_median', 'moving_average']),
    ParamDef('delay_filter_length', 'int', 10,
             label='Delay Filter Length',
             tooltip='Anzahl der Werte für den Delay-Filter (10 = Standard).',
             section='Interface', min_val=1, max_val=100),
    ParamDef('egressLatency', 'int', 0,
             label='Egress Latency',
             tooltip='Zusätzliche Ausgangs-Latenz in ns.\nFalls bekannt, korrigieren.',
             section='Interface', min_val=-1000000, max_val=1000000),
    ParamDef('ingressLatency', 'int', 0,
             label='Ingress Latency',
             tooltip='Zusätzliche Eingangs-Latenz in ns.\nFalls bekannt, korrigieren.',
             section='Interface', min_val=-1000000, max_val=1000000),
    ParamDef('boundary_clock_jbod', 'bool', 0,
             label='Boundary Clock JBOD',
             tooltip='JBOD-Modus für Boundary Clocks.\nAlle Ports unabhängig.',
             section='Interface'),
    ParamDef('phc_index', 'int', -1,
             label='PHC Index',
             tooltip='Index der PTP Hardware Clock.\n-1 = automatisch.',
             section='Interface', min_val=-1, max_val=255),
    ParamDef('productDescription', 'string', ';;',
             label='Product Description',
             tooltip='Produktbeschreibung für Clock-Beschreibung.',
             section='Interface'),
    ParamDef('revisionData', 'string', ';;',
             label='Revision Data',
             tooltip='Revisionsdaten für Clock-Beschreibung.',
             section='Interface'),
    ParamDef('manufacturerIdentity', 'string', '00:00:00',
             label='Manufacturer Identity',
             tooltip='Herstellerkennung (3-Byte OUI).',
             section='Interface'),
    ParamDef('userDescription', 'string', '',
             label='User Description',
             tooltip='Benutzerdefinierte Beschreibung des Clocks.',
             section='Interface'),
    ParamDef('timeSource', 'string', '0xA0',
             label='Time Source',
             tooltip='Zeitquelle:\n0xA0 = interne Oszillator (typisch).',
             section='Interface'),
]

PARAM_MAP = {p.key: p for p in CONFIG_PARAMS}

SECTION_ORDER = ['Quick', 'Default', 'Port', 'Runtime', 'Servo', 'Transport', 'Interface']


def get_params_for_section(section):
    return [p for p in CONFIG_PARAMS if p.section == section]
