__version__ = "1.0.0"
__app_name__ = "sync67"
__description__ = "A Linux desktop tool for managing, monitoring and configuring AES67 audio streaming with PipeWire."
__license__ = "MIT"
__author__ = "jaxcfgj"
